feat: 添加no codegen形式的 Fabaric 组件以及对应使用示例
react-native-oh-library/react-native-harmony-sample-package pull request #7
Opened 2024-08-02 09:02 UTC by dream-approaching

# Summary

请解释此次更改的 **动机**，以下是一些帮助您的要点：

- close #6 
- 添加非 codegen 形式的 Fabric 组件，包含以下内容
  - No Codegen ArkTS 形式的 Fabric 组件源码
  - No Codegen CAPI 形式的 Fabric 组件源码
  - tester 中的使用示例

## Test Plan

![image](https://github.com/user-attachments/assets/fa04e407-ba30-4839-a375-e56634870868)

## Checklist

- [x] 已经在设备和模拟器上测试通过
- [ ] 已经与 Android 或 iOS 平台做过效果/功能对比
- [ ] 已经添加了对应 API 的测试用例
- [ ] 已经更新了文档（如需要）
- [x] 更新了 JS/TS 代码 (如有)

2024-08-02 09:14 UTC, Louis-C7 requested changes

2024-08-02 09:14 UTC, Louis-C7 commented on no-codegen-sample-package/harmony/no_codegen_sample_package/src/main/cpp/forArkTS/NoCodegenPackage.cpp
NoCodegenArkTSSamplePackage.h

2024-08-02 09:14 UTC, Louis-C7 commented on no-codegen-sample-package/harmony/no_codegen_sample_package/src/main/cpp/forCAPI/BaseReactNativeOhTplCodegenSamplePackagePackage.h
> +#include "react/ComponentDescriptors.h"
#include <react/renderer/components/xxx/ComponentDescriptors.h> 保持这个目录结构

2024-08-02 09:14 UTC, Louis-C7 commented on tester/harmony/entry/src/main/cpp/CMakeLists.txt
> +#add_subdirectory("${OH_MODULE_DIR}/@react-native-oh-tpl/codegen-sample-package/src/main/cpp" ./codegen-sample-package)
为什么不放开？

2024-08-02 09:14 UTC, Louis-C7 commented on no-codegen-sample-package/package.json
> +  "version": "0.0.1-0.0.1",
0.0.1即可

2024-08-03 06:54 UTC, Louis-C7 requested changes

2024-08-03 06:54 UTC, Louis-C7 commented on no-codegen-sample-package/harmony/no_codegen_sample_package/src/main/cpp/forCAPI/CMakeLists.txt
> +file(GLOB_RECURSE codegened_cpp_SRC "${CMAKE_CURRENT_SOURCE_DIR}/**/*.cpp")
这里有点问题

2024-08-05 05:52 UTC, dream-approaching commented on no-codegen-sample-package/harmony/no_codegen_sample_package/src/main/cpp/forArkTS/NoCodegenPackage.cpp
已修改

2024-08-05 05:52 UTC, dream-approaching commented on no-codegen-sample-package/package.json
> +  "version": "0.0.1-0.0.1",
已修改

2024-08-05 06:59 UTC, dream-approaching commented on no-codegen-sample-package/harmony/no_codegen_sample_package/src/main/cpp/forCAPI/CMakeLists.txt
> +file(GLOB_RECURSE codegened_cpp_SRC "${CMAKE_CURRENT_SOURCE_DIR}/**/*.cpp")
已修改

2024-08-05 07:03 UTC, Louis-C7 approved these changes

2024-08-05 07:03 UTC, merged